/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';
import {
  IChord,
} from './model/IChord';


export namespace Components {
  interface AppChord {
    'chord': IChord;
  }
  interface AppChords {}
  interface AppRoot {}
  interface AppSelector {
    'list': string[];
  }
}

declare namespace LocalJSX {
  interface AppChord extends JSXBase.HTMLAttributes {
    'chord'?: IChord;
  }
  interface AppChords extends JSXBase.HTMLAttributes {}
  interface AppRoot extends JSXBase.HTMLAttributes {}
  interface AppSelector extends JSXBase.HTMLAttributes {
    'list'?: string[];
    'onSelectedChanged'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'app-chord': AppChord;
    'app-chords': AppChords;
    'app-root': AppRoot;
    'app-selector': AppSelector;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLAppChordElement extends Components.AppChord, HTMLStencilElement {}
  var HTMLAppChordElement: {
    prototype: HTMLAppChordElement;
    new (): HTMLAppChordElement;
  };

  interface HTMLAppChordsElement extends Components.AppChords, HTMLStencilElement {}
  var HTMLAppChordsElement: {
    prototype: HTMLAppChordsElement;
    new (): HTMLAppChordsElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSelectorElement extends Components.AppSelector, HTMLStencilElement {}
  var HTMLAppSelectorElement: {
    prototype: HTMLAppSelectorElement;
    new (): HTMLAppSelectorElement;
  };

  interface HTMLElementTagNameMap {
    'app-chord': HTMLAppChordElement;
    'app-chords': HTMLAppChordsElement;
    'app-root': HTMLAppRootElement;
    'app-selector': HTMLAppSelectorElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

